#!/usr/bin/bash
#bash script to run all files

# mqtt publishing scripts
python3 <path><sensor_name>.py &
#...

#start script to subscribe the topic and write to db
echo 'Start subscribing sensor data'
python3 <path>sub_db.py &
# home/pi/IoT/