#!/usr/bin/bash
#bash script to run all files

# mqtt publishing scripts
python3 <sensor_name>.py &
#...

#start script to subscribe the topic and write to db
echo 'Start subscribing sensor data'
python3 sub_db.py &